name: "Run npm tests"
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup App
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.15.0'
      - run: npm run setup
      - name: Run tests
        run: npm run tests
