name: "Generate TypeDoc files and publish to Github Pages"
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup App
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.15.0'
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
           # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm run setup
      - name: Run build step
        run: npm run build
      - name: Get pwd
        run: pwd
      - name: List root directory
        run: ls -la
      - name: List build directory
        run: ls -la build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'root'
          if-no-files-found: error
          path: '.'

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Getting artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'root'
          path: '.'
      - name: Get pwd
        run: pwd
      - name: List root directory
        run: ls -la
      - name: List build directory
        run: ls -la build
      - name: Install jest
        run: npm install jest --legacy-peer-deps
      - name: Run tests
        run: npm run test

  docs:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Getting artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'root'
          path: '.'
      - name: Get pwd
        run: pwd
      - name: List root directory
        run: ls -la
      - name: List build directory
        run: ls -la build
      - name: Generate documentation
        run: npm run docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
